# Generated by Django 4.2.5 on 2023-11-20 20:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('serial_num', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('date_watered', models.DateField(verbose_name='watered date')),
                ('timelapse_period', models.IntegerField()),
                ('timelapse_path', models.CharField(max_length=100)),
                ('image_count', models.IntegerField()),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_measured', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 20, 48, 57, 771626), verbose_name='measured date')),
                ('light', models.CharField(max_length=10)),
                ('temp', models.CharField(max_length=10)),
                ('humi', models.CharField(max_length=10)),
                ('watery', models.CharField(max_length=10)),
                ('ph', models.CharField(max_length=10, null=True)),
                ('is_img_exist', models.BooleanField(default=False)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plant')),
            ],
        ),
    ]
