# Generated by Django 4.2.5 on 2023-11-20 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_data_date_measured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_measured',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 20, 53, 41, 375394), verbose_name='measured date'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
    ]
